remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-feed

permalink: /:title/
owner:
  name: Amirsalar Darvishpour
#   avatar: hanlin.jpg
#  bio:
  email: amir.shdk@yahoo.com
  github: salar-shdk
  linkedin: salar-darvish

linkes:
  - title: "home"
    url: "/"
  - title: "experiences"
    url: "/experiences/"
